// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: groups/groups.proto

package groups

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateGroupRequest is the request for creating a new group
type CreateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserId is the ID of the user creating the group
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Name is the name of the group
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description is the description of the group
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Avatar is the URL to the group's avatar
	Avatar        string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_groups_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// GetGroupRequest is the request for retrieving a group
type GetGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// UserId is the ID of the user making the request (optional)
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_groups_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetGroupsRequest is the request for retrieving groups
type GetGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserId is the ID of the user making the request (optional)
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Query is the search query (optional)
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Page is the page number for pagination
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Limit is the number of groups per page
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsRequest) Reset() {
	*x = GetGroupsRequest{}
	mi := &file_groups_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest) ProtoMessage() {}

func (x *GetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetGroupsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetGroupsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UpdateGroupRequest is the request for updating a group
type UpdateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// UserId is the ID of the user updating the group
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Name is the updated name of the group (optional)
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description is the updated description of the group (optional)
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Avatar is the updated URL to the group's avatar (optional)
	Avatar        string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_groups_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// DeleteGroupRequest is the request for deleting a group
type DeleteGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// UserId is the ID of the user deleting the group
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_groups_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *DeleteGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// JoinGroupRequest is the request for joining a group
type JoinGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// UserId is the ID of the user joining the group
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_groups_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{5}
}

func (x *JoinGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// LeaveGroupRequest is the request for leaving a group
type LeaveGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// UserId is the ID of the user leaving the group
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupRequest) Reset() {
	*x = LeaveGroupRequest{}
	mi := &file_groups_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupRequest) ProtoMessage() {}

func (x *LeaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *LeaveGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetGroupMembersRequest is the request for retrieving group members
type GetGroupMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Page is the page number for pagination
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Limit is the number of members per page
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersRequest) Reset() {
	*x = GetGroupMembersRequest{}
	mi := &file_groups_groups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersRequest) ProtoMessage() {}

func (x *GetGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*GetGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{7}
}

func (x *GetGroupMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetGroupMembersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// CreateGroupPostRequest is the request for creating a post in a group
type CreateGroupPostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// UserId is the ID of the user creating the post
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Content is the content of the post
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Media is an array of media URLs (optional)
	Media         []string `protobuf:"bytes,4,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupPostRequest) Reset() {
	*x = CreateGroupPostRequest{}
	mi := &file_groups_groups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupPostRequest) ProtoMessage() {}

func (x *CreateGroupPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupPostRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupPostRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGroupPostRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateGroupPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateGroupPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateGroupPostRequest) GetMedia() []string {
	if x != nil {
		return x.Media
	}
	return nil
}

// GetGroupPostsRequest is the request for retrieving posts in a group
type GetGroupPostsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// UserId is the ID of the user making the request (optional)
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Page is the page number for pagination
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Limit is the number of posts per page
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupPostsRequest) Reset() {
	*x = GetGroupPostsRequest{}
	mi := &file_groups_groups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupPostsRequest) ProtoMessage() {}

func (x *GetGroupPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupPostsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupPostsRequest) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{9}
}

func (x *GetGroupPostsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetGroupPostsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetGroupPostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupPostsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GroupResponse is the response containing a group
type GroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Name is the name of the group
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description is the description of the group
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Avatar is the URL to the group's avatar
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// CreatorId is the ID of the user who created the group
	CreatorId string `protobuf:"bytes,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	// CreatorName is the name of the user who created the group
	CreatorName string `protobuf:"bytes,6,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	// MembersCount is the number of members in the group
	MembersCount int32 `protobuf:"varint,7,opt,name=members_count,json=membersCount,proto3" json:"members_count,omitempty"`
	// PostsCount is the number of posts in the group
	PostsCount int32 `protobuf:"varint,8,opt,name=posts_count,json=postsCount,proto3" json:"posts_count,omitempty"`
	// IsMember indicates if the requesting user is a member of the group
	IsMember bool `protobuf:"varint,9,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	// CreatedAt is the timestamp when the group was created
	CreatedAt string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// UpdatedAt is the timestamp when the group was last updated
	UpdatedAt     string `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupResponse) Reset() {
	*x = GroupResponse{}
	mi := &file_groups_groups_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResponse) ProtoMessage() {}

func (x *GroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResponse.ProtoReflect.Descriptor instead.
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{10}
}

func (x *GroupResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GroupResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupResponse) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *GroupResponse) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *GroupResponse) GetMembersCount() int32 {
	if x != nil {
		return x.MembersCount
	}
	return 0
}

func (x *GroupResponse) GetPostsCount() int32 {
	if x != nil {
		return x.PostsCount
	}
	return 0
}

func (x *GroupResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *GroupResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GroupResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// GetGroupsResponse is the response containing groups
type GetGroupsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Groups is an array of groups
	Groups []*GroupResponse `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	// TotalCount is the total number of groups
	TotalCount int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Page is the current page number
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// TotalPages is the total number of pages
	TotalPages    int32 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse) Reset() {
	*x = GetGroupsResponse{}
	mi := &file_groups_groups_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse) ProtoMessage() {}

func (x *GetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{11}
}

func (x *GetGroupsResponse) GetGroups() []*GroupResponse {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetGroupsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetGroupsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// DeleteGroupResponse is the response for deleting a group
type DeleteGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicates if the group was successfully deleted
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_groups_groups_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// JoinGroupResponse is the response for joining a group
type JoinGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicates if the user successfully joined the group
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// MembersCount is the updated number of members in the group
	MembersCount  int32 `protobuf:"varint,2,opt,name=members_count,json=membersCount,proto3" json:"members_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	mi := &file_groups_groups_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{13}
}

func (x *JoinGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinGroupResponse) GetMembersCount() int32 {
	if x != nil {
		return x.MembersCount
	}
	return 0
}

// LeaveGroupResponse is the response for leaving a group
type LeaveGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicates if the user successfully left the group
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// MembersCount is the updated number of members in the group
	MembersCount  int32 `protobuf:"varint,2,opt,name=members_count,json=membersCount,proto3" json:"members_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupResponse) Reset() {
	*x = LeaveGroupResponse{}
	mi := &file_groups_groups_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupResponse) ProtoMessage() {}

func (x *LeaveGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupResponse.ProtoReflect.Descriptor instead.
func (*LeaveGroupResponse) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{14}
}

func (x *LeaveGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveGroupResponse) GetMembersCount() int32 {
	if x != nil {
		return x.MembersCount
	}
	return 0
}

// GroupMemberResponse is the response containing a group member
type GroupMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserId is the ID of the member
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Name is the name of the member
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Avatar is the avatar URL of the member
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// Role is the role of the member in the group (creator, admin, member)
	Role string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// JoinedAt is the timestamp when the member joined the group
	JoinedAt      string `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberResponse) Reset() {
	*x = GroupMemberResponse{}
	mi := &file_groups_groups_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberResponse) ProtoMessage() {}

func (x *GroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberResponse.ProtoReflect.Descriptor instead.
func (*GroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{15}
}

func (x *GroupMemberResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupMemberResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupMemberResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupMemberResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GroupMemberResponse) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

// GetGroupMembersResponse is the response containing group members
type GetGroupMembersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Members is an array of group members
	Members []*GroupMemberResponse `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// TotalCount is the total number of members
	TotalCount int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Page is the current page number
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// TotalPages is the total number of pages
	TotalPages    int32 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersResponse) Reset() {
	*x = GetGroupMembersResponse{}
	mi := &file_groups_groups_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersResponse) ProtoMessage() {}

func (x *GetGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*GetGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{16}
}

func (x *GetGroupMembersResponse) GetMembers() []*GroupMemberResponse {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetGroupMembersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetGroupMembersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupMembersResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// GroupPostResponse is the response containing a group post
type GroupPostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PostId is the ID of the post
	PostId string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	// GroupId is the ID of the group
	GroupId string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// AuthorId is the ID of the user who created the post
	AuthorId string `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// AuthorName is the name of the user who created the post
	AuthorName string `protobuf:"bytes,4,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	// AuthorAvatar is the avatar URL of the user who created the post
	AuthorAvatar string `protobuf:"bytes,5,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar,omitempty"`
	// Content is the content of the post
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// Media is an array of media URLs
	Media []string `protobuf:"bytes,7,rep,name=media,proto3" json:"media,omitempty"`
	// LikesCount is the number of likes on the post
	LikesCount int32 `protobuf:"varint,8,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	// CommentsCount is the number of comments on the post
	CommentsCount int32 `protobuf:"varint,9,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	// IsLiked indicates if the requesting user has liked the post
	IsLiked bool `protobuf:"varint,10,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	// CreatedAt is the timestamp when the post was created
	CreatedAt string `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// UpdatedAt is the timestamp when the post was last updated
	UpdatedAt     string `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPostResponse) Reset() {
	*x = GroupPostResponse{}
	mi := &file_groups_groups_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPostResponse) ProtoMessage() {}

func (x *GroupPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPostResponse.ProtoReflect.Descriptor instead.
func (*GroupPostResponse) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{17}
}

func (x *GroupPostResponse) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GroupPostResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupPostResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *GroupPostResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *GroupPostResponse) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

func (x *GroupPostResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupPostResponse) GetMedia() []string {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *GroupPostResponse) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *GroupPostResponse) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *GroupPostResponse) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *GroupPostResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GroupPostResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// GetGroupPostsResponse is the response containing group posts
type GetGroupPostsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Posts is an array of group posts
	Posts []*GroupPostResponse `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	// TotalCount is the total number of posts
	TotalCount int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Page is the current page number
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// TotalPages is the total number of pages
	TotalPages    int32 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupPostsResponse) Reset() {
	*x = GetGroupPostsResponse{}
	mi := &file_groups_groups_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupPostsResponse) ProtoMessage() {}

func (x *GetGroupPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_groups_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupPostsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupPostsResponse) Descriptor() ([]byte, []int) {
	return file_groups_groups_proto_rawDescGZIP(), []int{18}
}

func (x *GetGroupPostsResponse) GetPosts() []*GroupPostResponse {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *GetGroupPostsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetGroupPostsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupPostsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_groups_groups_proto protoreflect.FileDescriptor

const file_groups_groups_proto_rawDesc = "" +
	"\n" +
	"\x13groups/groups.proto\x12\x06groups\"{\n" +
	"\x12CreateGroupRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"E\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"k\n" +
	"\x10GetGroupsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x96\x01\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\"H\n" +
	"\x12DeleteGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"F\n" +
	"\x10JoinGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x11LeaveGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"]\n" +
	"\x16GetGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"|\n" +
	"\x16CreateGroupPostRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05media\x18\x04 \x03(\tR\x05media\"t\n" +
	"\x14GetGroupPostsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xdb\x02\n" +
	"\rGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x05 \x01(\tR\tcreatorId\x12!\n" +
	"\fcreator_name\x18\x06 \x01(\tR\vcreatorName\x12#\n" +
	"\rmembers_count\x18\a \x01(\x05R\fmembersCount\x12\x1f\n" +
	"\vposts_count\x18\b \x01(\x05R\n" +
	"postsCount\x12\x1b\n" +
	"\tis_member\x18\t \x01(\bR\bisMember\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\x98\x01\n" +
	"\x11GetGroupsResponse\x12-\n" +
	"\x06groups\x18\x01 \x03(\v2\x15.groups.GroupResponseR\x06groups\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"/\n" +
	"\x13DeleteGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x11JoinGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rmembers_count\x18\x02 \x01(\x05R\fmembersCount\"S\n" +
	"\x12LeaveGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rmembers_count\x18\x02 \x01(\x05R\fmembersCount\"\x8b\x01\n" +
	"\x13GroupMemberResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\tR\bjoinedAt\"\xa6\x01\n" +
	"\x17GetGroupMembersResponse\x125\n" +
	"\amembers\x18\x01 \x03(\v2\x1b.groups.GroupMemberResponseR\amembers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xfb\x02\n" +
	"\x11GroupPostResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\x04 \x01(\tR\n" +
	"authorName\x12#\n" +
	"\rauthor_avatar\x18\x05 \x01(\tR\fauthorAvatar\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x14\n" +
	"\x05media\x18\a \x03(\tR\x05media\x12\x1f\n" +
	"\vlikes_count\x18\b \x01(\x05R\n" +
	"likesCount\x12%\n" +
	"\x0ecomments_count\x18\t \x01(\x05R\rcommentsCount\x12\x19\n" +
	"\bis_liked\x18\n" +
	" \x01(\bR\aisLiked\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\x9e\x01\n" +
	"\x15GetGroupPostsResponse\x12/\n" +
	"\x05posts\x18\x01 \x03(\v2\x19.groups.GroupPostResponseR\x05posts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages2\xcf\x05\n" +
	"\fGroupService\x12@\n" +
	"\vCreateGroup\x12\x1a.groups.CreateGroupRequest\x1a\x15.groups.GroupResponse\x12:\n" +
	"\bGetGroup\x12\x17.groups.GetGroupRequest\x1a\x15.groups.GroupResponse\x12@\n" +
	"\tGetGroups\x12\x18.groups.GetGroupsRequest\x1a\x19.groups.GetGroupsResponse\x12@\n" +
	"\vUpdateGroup\x12\x1a.groups.UpdateGroupRequest\x1a\x15.groups.GroupResponse\x12F\n" +
	"\vDeleteGroup\x12\x1a.groups.DeleteGroupRequest\x1a\x1b.groups.DeleteGroupResponse\x12@\n" +
	"\tJoinGroup\x12\x18.groups.JoinGroupRequest\x1a\x19.groups.JoinGroupResponse\x12C\n" +
	"\n" +
	"LeaveGroup\x12\x19.groups.LeaveGroupRequest\x1a\x1a.groups.LeaveGroupResponse\x12R\n" +
	"\x0fGetGroupMembers\x12\x1e.groups.GetGroupMembersRequest\x1a\x1f.groups.GetGroupMembersResponse\x12L\n" +
	"\x0fCreateGroupPost\x12\x1e.groups.CreateGroupPostRequest\x1a\x19.groups.GroupPostResponse\x12L\n" +
	"\rGetGroupPosts\x12\x1c.groups.GetGroupPostsRequest\x1a\x1d.groups.GetGroupPostsResponseB\x15Z\x13common/proto/groupsb\x06proto3"

var (
	file_groups_groups_proto_rawDescOnce sync.Once
	file_groups_groups_proto_rawDescData []byte
)

func file_groups_groups_proto_rawDescGZIP() []byte {
	file_groups_groups_proto_rawDescOnce.Do(func() {
		file_groups_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_groups_groups_proto_rawDesc), len(file_groups_groups_proto_rawDesc)))
	})
	return file_groups_groups_proto_rawDescData
}

var file_groups_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_groups_groups_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),      // 0: groups.CreateGroupRequest
	(*GetGroupRequest)(nil),         // 1: groups.GetGroupRequest
	(*GetGroupsRequest)(nil),        // 2: groups.GetGroupsRequest
	(*UpdateGroupRequest)(nil),      // 3: groups.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),      // 4: groups.DeleteGroupRequest
	(*JoinGroupRequest)(nil),        // 5: groups.JoinGroupRequest
	(*LeaveGroupRequest)(nil),       // 6: groups.LeaveGroupRequest
	(*GetGroupMembersRequest)(nil),  // 7: groups.GetGroupMembersRequest
	(*CreateGroupPostRequest)(nil),  // 8: groups.CreateGroupPostRequest
	(*GetGroupPostsRequest)(nil),    // 9: groups.GetGroupPostsRequest
	(*GroupResponse)(nil),           // 10: groups.GroupResponse
	(*GetGroupsResponse)(nil),       // 11: groups.GetGroupsResponse
	(*DeleteGroupResponse)(nil),     // 12: groups.DeleteGroupResponse
	(*JoinGroupResponse)(nil),       // 13: groups.JoinGroupResponse
	(*LeaveGroupResponse)(nil),      // 14: groups.LeaveGroupResponse
	(*GroupMemberResponse)(nil),     // 15: groups.GroupMemberResponse
	(*GetGroupMembersResponse)(nil), // 16: groups.GetGroupMembersResponse
	(*GroupPostResponse)(nil),       // 17: groups.GroupPostResponse
	(*GetGroupPostsResponse)(nil),   // 18: groups.GetGroupPostsResponse
}
var file_groups_groups_proto_depIdxs = []int32{
	10, // 0: groups.GetGroupsResponse.groups:type_name -> groups.GroupResponse
	15, // 1: groups.GetGroupMembersResponse.members:type_name -> groups.GroupMemberResponse
	17, // 2: groups.GetGroupPostsResponse.posts:type_name -> groups.GroupPostResponse
	0,  // 3: groups.GroupService.CreateGroup:input_type -> groups.CreateGroupRequest
	1,  // 4: groups.GroupService.GetGroup:input_type -> groups.GetGroupRequest
	2,  // 5: groups.GroupService.GetGroups:input_type -> groups.GetGroupsRequest
	3,  // 6: groups.GroupService.UpdateGroup:input_type -> groups.UpdateGroupRequest
	4,  // 7: groups.GroupService.DeleteGroup:input_type -> groups.DeleteGroupRequest
	5,  // 8: groups.GroupService.JoinGroup:input_type -> groups.JoinGroupRequest
	6,  // 9: groups.GroupService.LeaveGroup:input_type -> groups.LeaveGroupRequest
	7,  // 10: groups.GroupService.GetGroupMembers:input_type -> groups.GetGroupMembersRequest
	8,  // 11: groups.GroupService.CreateGroupPost:input_type -> groups.CreateGroupPostRequest
	9,  // 12: groups.GroupService.GetGroupPosts:input_type -> groups.GetGroupPostsRequest
	10, // 13: groups.GroupService.CreateGroup:output_type -> groups.GroupResponse
	10, // 14: groups.GroupService.GetGroup:output_type -> groups.GroupResponse
	11, // 15: groups.GroupService.GetGroups:output_type -> groups.GetGroupsResponse
	10, // 16: groups.GroupService.UpdateGroup:output_type -> groups.GroupResponse
	12, // 17: groups.GroupService.DeleteGroup:output_type -> groups.DeleteGroupResponse
	13, // 18: groups.GroupService.JoinGroup:output_type -> groups.JoinGroupResponse
	14, // 19: groups.GroupService.LeaveGroup:output_type -> groups.LeaveGroupResponse
	16, // 20: groups.GroupService.GetGroupMembers:output_type -> groups.GetGroupMembersResponse
	17, // 21: groups.GroupService.CreateGroupPost:output_type -> groups.GroupPostResponse
	18, // 22: groups.GroupService.GetGroupPosts:output_type -> groups.GetGroupPostsResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_groups_groups_proto_init() }
func file_groups_groups_proto_init() {
	if File_groups_groups_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_groups_groups_proto_rawDesc), len(file_groups_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_groups_groups_proto_goTypes,
		DependencyIndexes: file_groups_groups_proto_depIdxs,
		MessageInfos:      file_groups_groups_proto_msgTypes,
	}.Build()
	File_groups_groups_proto = out.File
	file_groups_groups_proto_goTypes = nil
	file_groups_groups_proto_depIdxs = nil
}
