// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: users/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest is the request for registering a new user
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider is the OAuth provider (google or microsoft)
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Token is the OAuth token
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RegisterResponse is the response for registering a new user
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserId is the unique identifier for the user
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// AccessToken is the JWT token for authentication
	AccessToken   string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// LoginRequest is the request for logging in a user
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider is the OAuth provider (google or microsoft)
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Token is the OAuth token
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// LoginResponse is the response for logging in a user
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserId is the unique identifier for the user
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// AccessToken is the JWT token for authentication
	AccessToken   string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// GetProfileRequest is the request for getting a user's profile
type GetProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserId is the unique identifier for the user
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_users_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UpdateProfileRequest is the request for updating a user's profile
type UpdateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserId is the unique identifier for the user
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Name is the user's name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Avatar is the URL to the user's avatar
	Avatar        string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_users_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// ProfileResponse is the response containing a user's profile
type ProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserId is the unique identifier for the user
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Name is the user's name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Email is the user's email
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Avatar is the URL to the user's avatar
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// CreatedAt is the timestamp when the user was created
	CreatedAt     string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_users_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfileResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ProfileResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// GoogleLoginRequest is the request for generating a Google OAuth URL
type GoogleLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RedirectURL is the URL to redirect to after authentication (optional)
	RedirectUrl   string `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleLoginRequest) Reset() {
	*x = GoogleLoginRequest{}
	mi := &file_users_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginRequest) ProtoMessage() {}

func (x *GoogleLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginRequest.ProtoReflect.Descriptor instead.
func (*GoogleLoginRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{7}
}

func (x *GoogleLoginRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

// MicrosoftLoginRequest is the request for generating a Microsoft OAuth URL
type MicrosoftLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RedirectURL is the URL to redirect to after authentication (optional)
	RedirectUrl   string `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicrosoftLoginRequest) Reset() {
	*x = MicrosoftLoginRequest{}
	mi := &file_users_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicrosoftLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicrosoftLoginRequest) ProtoMessage() {}

func (x *MicrosoftLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicrosoftLoginRequest.ProtoReflect.Descriptor instead.
func (*MicrosoftLoginRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{8}
}

func (x *MicrosoftLoginRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

// OAuthURLResponse is the response containing an OAuth URL
type OAuthURLResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL is the OAuth URL to redirect the user to
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// State is the state token for CSRF protection
	State         string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthURLResponse) Reset() {
	*x = OAuthURLResponse{}
	mi := &file_users_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthURLResponse) ProtoMessage() {}

func (x *OAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthURLResponse.ProtoReflect.Descriptor instead.
func (*OAuthURLResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{9}
}

func (x *OAuthURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OAuthURLResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// OAuthCallbackRequest is the request for handling an OAuth callback
type OAuthCallbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State is the state token for CSRF protection
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// Code is the authorization code from the OAuth provider
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthCallbackRequest) Reset() {
	*x = OAuthCallbackRequest{}
	mi := &file_users_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthCallbackRequest) ProtoMessage() {}

func (x *OAuthCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthCallbackRequest.ProtoReflect.Descriptor instead.
func (*OAuthCallbackRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{10}
}

func (x *OAuthCallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OAuthCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// ValidateStateTokenRequest is the request for validating a state token
type ValidateStateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State is the state token to validate
	State         string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateStateTokenRequest) Reset() {
	*x = ValidateStateTokenRequest{}
	mi := &file_users_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStateTokenRequest) ProtoMessage() {}

func (x *ValidateStateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateStateTokenRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateStateTokenRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// ValidateStateTokenResponse is the response for validating a state token
type ValidateStateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Valid indicates whether the state token is valid
	Valid         bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateStateTokenResponse) Reset() {
	*x = ValidateStateTokenResponse{}
	mi := &file_users_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStateTokenResponse) ProtoMessage() {}

func (x *ValidateStateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateStateTokenResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateStateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// SignoutRequest is the request for signing out a user
type SignoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token is the JWT token to invalidate
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignoutRequest) Reset() {
	*x = SignoutRequest{}
	mi := &file_users_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignoutRequest) ProtoMessage() {}

func (x *SignoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignoutRequest.ProtoReflect.Descriptor instead.
func (*SignoutRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{13}
}

func (x *SignoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// SignoutResponse is the response for signing out a user
type SignoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicates whether the signout was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignoutResponse) Reset() {
	*x = SignoutResponse{}
	mi := &file_users_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignoutResponse) ProtoMessage() {}

func (x *SignoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignoutResponse.ProtoReflect.Descriptor instead.
func (*SignoutResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{14}
}

func (x *SignoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_users_users_proto protoreflect.FileDescriptor

const file_users_users_proto_rawDesc = "" +
	"\n" +
	"\x11users/users.proto\x12\x05users\"C\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"N\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"@\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"K\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"[\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"\x8b\x01\n" +
	"\x0fProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"7\n" +
	"\x12GoogleLoginRequest\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\":\n" +
	"\x15MicrosoftLoginRequest\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\":\n" +
	"\x10OAuthURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"@\n" +
	"\x14OAuthCallbackRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"1\n" +
	"\x19ValidateStateTokenRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"2\n" +
	"\x1aValidateStateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"&\n" +
	"\x0eSignoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"+\n" +
	"\x0fSignoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb2\x05\n" +
	"\vUserService\x12;\n" +
	"\bRegister\x12\x16.users.RegisterRequest\x1a\x17.users.RegisterResponse\x122\n" +
	"\x05Login\x12\x13.users.LoginRequest\x1a\x14.users.LoginResponse\x12>\n" +
	"\n" +
	"GetProfile\x12\x18.users.GetProfileRequest\x1a\x16.users.ProfileResponse\x12D\n" +
	"\rUpdateProfile\x12\x1b.users.UpdateProfileRequest\x1a\x16.users.ProfileResponse\x12A\n" +
	"\vGoogleLogin\x12\x19.users.GoogleLoginRequest\x1a\x17.users.OAuthURLResponse\x12G\n" +
	"\x0eMicrosoftLogin\x12\x1c.users.MicrosoftLoginRequest\x1a\x17.users.OAuthURLResponse\x12C\n" +
	"\x0eGoogleCallback\x12\x1b.users.OAuthCallbackRequest\x1a\x14.users.LoginResponse\x12F\n" +
	"\x11MicrosoftCallback\x12\x1b.users.OAuthCallbackRequest\x1a\x14.users.LoginResponse\x12Y\n" +
	"\x12ValidateStateToken\x12 .users.ValidateStateTokenRequest\x1a!.users.ValidateStateTokenResponse\x128\n" +
	"\aSignout\x12\x15.users.SignoutRequest\x1a\x16.users.SignoutResponseB\x14Z\x12common/proto/usersb\x06proto3"

var (
	file_users_users_proto_rawDescOnce sync.Once
	file_users_users_proto_rawDescData []byte
)

func file_users_users_proto_rawDescGZIP() []byte {
	file_users_users_proto_rawDescOnce.Do(func() {
		file_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)))
	})
	return file_users_users_proto_rawDescData
}

var file_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_users_users_proto_goTypes = []any{
	(*RegisterRequest)(nil),            // 0: users.RegisterRequest
	(*RegisterResponse)(nil),           // 1: users.RegisterResponse
	(*LoginRequest)(nil),               // 2: users.LoginRequest
	(*LoginResponse)(nil),              // 3: users.LoginResponse
	(*GetProfileRequest)(nil),          // 4: users.GetProfileRequest
	(*UpdateProfileRequest)(nil),       // 5: users.UpdateProfileRequest
	(*ProfileResponse)(nil),            // 6: users.ProfileResponse
	(*GoogleLoginRequest)(nil),         // 7: users.GoogleLoginRequest
	(*MicrosoftLoginRequest)(nil),      // 8: users.MicrosoftLoginRequest
	(*OAuthURLResponse)(nil),           // 9: users.OAuthURLResponse
	(*OAuthCallbackRequest)(nil),       // 10: users.OAuthCallbackRequest
	(*ValidateStateTokenRequest)(nil),  // 11: users.ValidateStateTokenRequest
	(*ValidateStateTokenResponse)(nil), // 12: users.ValidateStateTokenResponse
	(*SignoutRequest)(nil),             // 13: users.SignoutRequest
	(*SignoutResponse)(nil),            // 14: users.SignoutResponse
}
var file_users_users_proto_depIdxs = []int32{
	0,  // 0: users.UserService.Register:input_type -> users.RegisterRequest
	2,  // 1: users.UserService.Login:input_type -> users.LoginRequest
	4,  // 2: users.UserService.GetProfile:input_type -> users.GetProfileRequest
	5,  // 3: users.UserService.UpdateProfile:input_type -> users.UpdateProfileRequest
	7,  // 4: users.UserService.GoogleLogin:input_type -> users.GoogleLoginRequest
	8,  // 5: users.UserService.MicrosoftLogin:input_type -> users.MicrosoftLoginRequest
	10, // 6: users.UserService.GoogleCallback:input_type -> users.OAuthCallbackRequest
	10, // 7: users.UserService.MicrosoftCallback:input_type -> users.OAuthCallbackRequest
	11, // 8: users.UserService.ValidateStateToken:input_type -> users.ValidateStateTokenRequest
	13, // 9: users.UserService.Signout:input_type -> users.SignoutRequest
	1,  // 10: users.UserService.Register:output_type -> users.RegisterResponse
	3,  // 11: users.UserService.Login:output_type -> users.LoginResponse
	6,  // 12: users.UserService.GetProfile:output_type -> users.ProfileResponse
	6,  // 13: users.UserService.UpdateProfile:output_type -> users.ProfileResponse
	9,  // 14: users.UserService.GoogleLogin:output_type -> users.OAuthURLResponse
	9,  // 15: users.UserService.MicrosoftLogin:output_type -> users.OAuthURLResponse
	3,  // 16: users.UserService.GoogleCallback:output_type -> users.LoginResponse
	3,  // 17: users.UserService.MicrosoftCallback:output_type -> users.LoginResponse
	12, // 18: users.UserService.ValidateStateToken:output_type -> users.ValidateStateTokenResponse
	14, // 19: users.UserService.Signout:output_type -> users.SignoutResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_users_users_proto_init() }
func file_users_users_proto_init() {
	if File_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_users_proto_goTypes,
		DependencyIndexes: file_users_users_proto_depIdxs,
		MessageInfos:      file_users_users_proto_msgTypes,
	}.Build()
	File_users_users_proto = out.File
	file_users_users_proto_goTypes = nil
	file_users_users_proto_depIdxs = nil
}
